import Head from 'next/head'

import { Navbar, About, Contact, Footer } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Zach Collins Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png"/>
      </Head>

      <main className='bg-white flex flex-col h-screen'>
        <Navbar/>

        <section className='flex flex-col px-4 md:px-20 lg:px-40 xl:px-60 h-screen justify-between'>
          <About/>
          <Contact/>

          <Footer/>
        </section>
      </main>
    </>
  )
}
