import Head from 'next/head'

import { Navbar, About, Footer } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Zach Collins Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40'>
        <section className='flex flex-col h-screen justify-between'>
          <div>
            <Navbar/>
            <About/>
          </div>

          <Footer/>
        </section>
      </main>
    </>
  )
}
